# Generated by Django 6.0.5 on 2026-05-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_hours', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('fatigue_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('sleep_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDecision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_plan', models.CharField(max_length=50)),
                ('score', models.FloatField(max_length=10)),
                ('metrix', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedlyapp.schedulerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, max_length=200)),
                ('remaining_hours', models.FloatField(max_length=10)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('energy_required', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delayed', 'Delayed'), ('finished', 'Finished'), ('dropped', 'Dropped'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('not yet started', 'Not Yet Started')], default='not yet started', max_length=20)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedlyapp.userstate')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_task_hours', models.FloatField(max_length=10)),
                ('overload_hours', models.FloatField(max_length=10)),
                ('capacity_hours', models.FloatField(max_length=10)),
                ('overloaded', models.BooleanField()),
                ('effective_energy', models.IntegerField(max_length=10)),
                ('schedule_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedlyapp.schedulerequest')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedlyapp.userstate')),
            ],
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedlyapp.userstate'),
        ),
    ]
