# Generated by Django 6.0.5 on 2026-05-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandecision',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='available_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schedulestate',
            name='capacity_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schedulestate',
            name='effective_energy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedulestate',
            name='overload_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schedulestate',
            name='total_task_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='remaining_hours',
            field=models.FloatField(),
        ),
    ]
