# Generated by Django 6.0.5 on 2026-05-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0002_alter_plandecision_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandecision',
            old_name='schedule_request_id',
            new_name='schedule_request',
        ),
        migrations.RenameField(
            model_name='schedulerequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='schedulestate',
            old_name='schedule_request_id',
            new_name='schedule_request',
        ),
        migrations.RenameField(
            model_name='schedulestate',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
