# Generated by Django 6.0.5 on 2026-05-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0003_rename_schedule_request_id_plandecision_schedule_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delayed', 'Delayed'), ('finished', 'Finished'), ('dropped', 'Dropped'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('not_yet_started', 'Not Yet Started')], default='not_yet_started', max_length=20),
        ),
    ]
