# Generated by Django 6.0.5 on 2026-05-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0004_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandecision',
            old_name='metrix',
            new_name='metrics',
        ),
    ]
