# Generated by Django 6.0.5 on 2026-05-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0005_rename_metrix_plandecision_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulestate',
            name='fatigue_score',
            field=models.FloatField(default=0.1),
        ),
    ]
