# Generated by Django 6.0.5 on 2026-05-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedlyapp', '0006_schedulestate_fatigue_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delayed', 'Delayed'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('dropped', 'Dropped'), ('cancelled', 'Cancelled'), ('missed', 'Missed'), ('not_yet_started', 'Not Yet Started')], default='not_yet_started', max_length=20),
        ),
    ]
