# Generated by Django 6.0.5 on 2026-05-09 00:00

from django.db import migrations, models


def backfill_task_start_dates(apps, schema_editor):
    Task = apps.get_model("schedlyapp", "Task")
    for task in Task.objects.all():
        task.start_date = task.deadline or task.created_at
        task.save(update_fields=["start_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("schedlyapp", "0007_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_task_start_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
