import React, { useState, useEffect } from "react";
import {
  BatteryFull,
  BatteryMedium,
  BatteryLow,
  Frown,
  Meh,
  Smile,
} from "lucide-react";
import { Task, Intensity } from "../types";
import {
  UserState as ApiUserState,
  generatePlan,
  GeneratePlanResponse,
} from "@/lib/endpoints";

interface UserStatusWidgetProps {
  onAddTask?: (
    task: Omit<Task, "id" | "scheduleCondition">,
  ) => Promise<void> | void;
  tasks?: Task[];
  initialUserState?: ApiUserState | null;
  onSaveUserState?: (
    payload: Pick<
      ApiUserState,
      "energy_level" | "fatigue_level" | "sleep_hours"
    >,
  ) => Promise<void> | void;
}

interface SuggestedAction {
  task_id: number;
  action: string;
  new_hours?: number;
}

interface SuggestedPlan {
  plan_type: string;
  stance: string;
  actions: SuggestedAction[];
}

interface SuggestionsPayload {
  reasoning: string;
  plans: SuggestedPlan[];
}

const enumToSliderValue = (
  level: ApiUserState["energy_level"] | ApiUserState["fatigue_level"],
) => {
  if (level === "low") return 20;
  if (level === "high") return 80;
  return 50;
};

const sliderValueToEnum = (value: number): ApiUserState["energy_level"] => {
  if (value <= 33) return "low";
  if (value <= 66) return "medium";
  return "high";
};

export function UserStatusWidget({
  onAddTask,
  tasks = [],
  initialUserState,
  onSaveUserState,
}: UserStatusWidgetProps) {
  const [savedHours, setSavedHours] = useState<number>(8);
  const [savedSleep, setSavedSleep] = useState<number>(8);
  const [savedFatigue, setSavedFatigue] = useState<number>(30);
  const [savedEnergy, setSavedEnergy] = useState<number>(70);

  const [hours, setHours] = useState<number>(8);
  const [sleep, setSleep] = useState<number>(8);
  const [fatigue, setFatigue] = useState<number>(30);
  const [energy, setEnergy] = useState<number>(70);

  const [showPrompt, setShowPrompt] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [isLoadingSuggestions, setIsLoadingSuggestions] = useState(false);
  // "waiting" gives immediate feedback before network starts; "fetching" is active API request.
  const [suggestionsPhase, setSuggestionsPhase] = useState<
    "idle" | "waiting" | "fetching"
  >("idle");
  const [showFinalConfirm, setShowFinalConfirm] = useState(false);
  const [selectedPlan, setSelectedPlan] = useState<SuggestedPlan | null>(null);
  const [suggestionsData, setSuggestionsData] = useState<SuggestionsPayload>({
    reasoning: "",
    plans: [],
  });
  const [suggestionsError, setSuggestionsError] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<"idle" | "success" | "error">(
    "idle",
  );

  // Accept both the new API shape (reasoning/plans) and legacy backend shape (best_plan).
  const normalizeSuggestions = (
    payload: GeneratePlanResponse,
  ): SuggestionsPayload => {
    if (payload.reasoning && Array.isArray(payload.plans)) {
      return {
        reasoning: payload.reasoning,
        plans: payload.plans.map((plan) => ({
          plan_type: plan.plan_type ?? "unknown",
          stance: plan.stance ?? "",
          actions: Array.isArray(plan.actions)
            ? plan.actions.map((action) => ({
                task_id: Number(action.task_id),
                action: action.action,
                new_hours: action.new_hours,
              }))
            : [],
        })),
      };
    }

    const fallbackPlan =
      payload.best_plan?.selected_plan && payload.best_plan
        ? [
            {
              plan_type: payload.best_plan.selected_plan,
              stance: "Generated by planning pipeline.",
              actions: [],
            },
          ]
        : [];

    return {
      reasoning: "No reasoning returned by API.",
      plans: fallbackPlan,
    };
  };

  // Enables resolving API action.task_id into human-readable task names in the modal.
  const taskLookup = tasks.reduce<Record<number, Task>>((acc, task) => {
    const taskId = Number(task.id);
    if (!Number.isNaN(taskId)) acc[taskId] = task;
    return acc;
  }, {});

  // Creates a reasonable UI intensity when importing API plan actions as tasks.
  const actionToIntensity = (action: string): Intensity => {
    if (action === "drop") return "Easy";
    if (action === "compress") return "Medium";
    return "Hard";
  };

  useEffect(() => {
    if (
      hours !== savedHours ||
      sleep !== savedSleep ||
      fatigue !== savedFatigue ||
      energy !== savedEnergy
    ) {
      setShowPrompt(true);
    } else {
      setShowPrompt(false);
    }
  }, [
    hours,
    sleep,
    fatigue,
    energy,
    savedHours,
    savedSleep,
    savedFatigue,
    savedEnergy,
  ]);

  // Initialize frontend UI controls using saved user data from the Django backend.
  useEffect(() => {
    if (!initialUserState) return;

    const nextSleep = Math.max(
      0,
      Math.min(24, Number(initialUserState.sleep_hours) || 0),
    );
    const nextFatigue = enumToSliderValue(initialUserState.fatigue_level);
    const nextEnergy = enumToSliderValue(initialUserState.energy_level);

    setSavedSleep(nextSleep);
    setSavedFatigue(nextFatigue);
    setSavedEnergy(nextEnergy);

    setSleep(nextSleep);
    setFatigue(nextFatigue);
    setEnergy(nextEnergy);
  }, [initialUserState]);

  const handleCancelPrompt = () => {
    setHours(savedHours);
    setSleep(savedSleep);
    setFatigue(savedFatigue);
    setEnergy(savedEnergy);
    setShowPrompt(false);
  };

  // Save user state to Django and then show task suggestions modal.
  const handleSave = async () => {
    setShowPrompt(false);

    try {
      await onSaveUserState?.({
        energy_level: sliderValueToEnum(energy),
        fatigue_level: sliderValueToEnum(fatigue),
        sleep_hours: Math.round(sleep),
      });
      setSavedHours(hours);
      setSavedSleep(sleep);
      setSavedFatigue(fatigue);
      setSavedEnergy(energy);
      setSaveStatus("success");
    } catch (error) {
      setSaveStatus("error");
      setShowPrompt(true);
      console.error(error);
      return;
    }

    // Open modal immediately so users can see waiting/fetching placeholders.
    setShowSuggestions(true);
    setIsLoadingSuggestions(true);
    setSuggestionsPhase("waiting");
    setSuggestionsError(null);
    setSelectedPlan(null);

    try {
      if (!initialUserState?.id) {
        throw new Error("Missing user id for generate_plan.");
      }

      // Short staged delay so "waiting" is visible before "fetching data".
      await new Promise((resolve) => setTimeout(resolve, 450));
      setSuggestionsPhase("fetching");

      const planPayload = await generatePlan({
        user: initialUserState.id,
        available_hours: Math.max(0, Number(hours) || 0),
      });

      const normalized = normalizeSuggestions(planPayload);
      setSuggestionsData(normalized);
      if (normalized.plans.length === 0) {
        setSuggestionsError("No plans were returned by the API.");
      }
    } catch (error) {
      // Keep the 3 placeholder cards visible on failures instead of collapsing the layout.
      setSuggestionsData({ reasoning: "", plans: [] });
      setSuggestionsError("Could not load Suggested Task List from API.");
      console.error(error);
    } finally {
      setIsLoadingSuggestions(false);
      setSuggestionsPhase("idle");
    }
  };

  useEffect(() => {
    if (saveStatus === "idle") return;
    const timeoutId = setTimeout(() => setSaveStatus("idle"), 2200);
    return () => clearTimeout(timeoutId);
  }, [saveStatus]);

  const handleSelectList = (plan: SuggestedPlan) => {
    setSelectedPlan(plan);
    setShowFinalConfirm(true);
  };

  const handleFinalConfirm = () => {
    if (onAddTask && selectedPlan) {
      // Expected behavior: selecting a plan creates tasks that flow into the shared Dashboard state,
      // which keeps Calendar, To-Do List, and Progress graph synchronized.
      selectedPlan.actions.forEach((actionItem) => {
        const mappedTask = taskLookup[actionItem.task_id];
        const mappedName = mappedTask?.name ?? `Task #${actionItem.task_id}`;
        const hourSuffix =
          typeof actionItem.new_hours === "number"
            ? ` | hrs: ${actionItem.new_hours}`
            : "";

        onAddTask({
          name: mappedName,
          description: `Action: ${actionItem.action}${hourSuffix}`,
          startDate: new Date().toISOString().split("T")[0],
          deadline: new Date().toISOString().split("T")[0],
          intensity: actionToIntensity(actionItem.action),
          status: "not yet started",
        });
      });
    }
    setShowFinalConfirm(false);
    setShowSuggestions(false);
    setSelectedPlan(null);
  };

  const handleFinalCancel = () => {
    setShowFinalConfirm(false);
  };

  const getEnergyIcon = () => {
    if (energy > 66)
      return <BatteryFull className="text-[#7FB77E]" size={20} />;
    if (energy > 33)
      return <BatteryMedium className="text-yellow-500" size={20} />;
    return <BatteryLow className="text-red-400" size={20} />;
  };

  const getFatigueIcon = () => {
    if (fatigue > 66) return <Frown className="text-red-400" size={20} />;
    if (fatigue > 33) return <Meh className="text-yellow-500" size={20} />;
    return <Smile className="text-[#7FB77E]" size={20} />;
  };

  return (
    <div className="bg-[#E3EFE6] p-4 rounded-xl shadow-sm border border-[#BFD8B8] relative">
      <h2 className="text-lg font-bold text-[#2F3E34] mb-3">User Status</h2>

      {/* Inline Save Prompt Banner */}
      {showPrompt && (
        <div className="absolute -top-12 left-0 right-0 bg-[#2F3E34] text-white p-3 rounded-lg shadow-xl flex items-center justify-between z-10 animate-in fade-in slide-in-from-bottom-2">
          <span className="text-sm font-medium">
            Do you wish to save changes?
          </span>
          <div className="flex gap-2">
            <button
              onClick={handleCancelPrompt}
              className="text-xs px-3 py-1.5 rounded bg-white/10 hover:bg-white/20 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              className="text-xs px-3 py-1.5 rounded bg-[#7FB77E] hover:bg-[#68a367] transition-colors font-bold"
            >
              Save
            </button>
          </div>
        </div>
      )}

      {saveStatus === "success" && (
        <div className="absolute -top-12 left-0 right-0 bg-[#7FB77E] text-white p-3 rounded-lg shadow-xl z-10 animate-in fade-in slide-in-from-bottom-2 text-sm font-medium">
          User state saved to Django.
        </div>
      )}

      {saveStatus === "error" && (
        <div className="absolute -top-12 left-0 right-0 bg-red-600 text-white p-3 rounded-lg shadow-xl z-10 animate-in fade-in slide-in-from-bottom-2 text-sm font-medium">
          Failed to save user state. Please try again.
        </div>
      )}

      <div className="space-y-4">
        {/* Top row: Hours and Sleep */}
        <div className="flex gap-4">
          <div className="flex-1">
            <label className="block text-xs font-medium text-[#2F3E34] mb-1">
              Hours Available
            </label>
            <input
              type="number"
              value={hours}
              onChange={(e) => setHours(Number(e.target.value))}
              className="bg-[#F4F7F5] border border-[#BFD8B8] text-[#2F3E34] text-sm rounded-lg focus:ring-[#7FB77E] focus:border-[#7FB77E] outline-none block w-full p-1.5"
              min="0"
              max="24"
            />
          </div>
          <div className="flex-1">
            <label className="block text-xs font-medium text-[#2F3E34] mb-1">
              Total Sleep (hrs)
            </label>
            <input
              type="number"
              value={sleep}
              onChange={(e) => setSleep(Number(e.target.value))}
              className="bg-[#F4F7F5] border border-[#BFD8B8] text-[#2F3E34] text-sm rounded-lg focus:ring-[#7FB77E] focus:border-[#7FB77E] outline-none block w-full p-1.5"
              min="0"
              max="24"
            />
          </div>
        </div>

        {/* Bottom row: Fatigue and Energy */}
        <div className="flex gap-4">
          <div className="flex-1">
            <div className="flex justify-between items-center mb-1">
              <label className="block text-xs font-medium text-[#2F3E34]">
                Fatigue
              </label>
              {getFatigueIcon()}
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={fatigue}
              onChange={(e) => setFatigue(Number(e.target.value))}
              className="w-full h-1.5 bg-[#BFD8B8] rounded-lg appearance-none cursor-pointer accent-[#7FB77E]"
            />
          </div>

          <div className="flex-1">
            <div className="flex justify-between items-center mb-1">
              <label className="block text-xs font-medium text-[#2F3E34]">
                Energy
              </label>
              {getEnergyIcon()}
            </div>
            <input
              type="range"
              min="0"
              max="100"
              value={energy}
              onChange={(e) => setEnergy(Number(e.target.value))}
              className="w-full h-1.5 bg-[#BFD8B8] rounded-lg appearance-none cursor-pointer accent-[#7FB77E]"
            />
          </div>
        </div>
      </div>

      {/* Suggestions Modal */}
      {showSuggestions && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-[#2F3E34]/40 backdrop-blur-sm">
          <div className="bg-[#F4F7F5] rounded-xl shadow-xl border border-[#BFD8B8] w-full max-w-5xl overflow-hidden animate-in zoom-in-95">
            <div className="p-5 border-b border-[#BFD8B8] bg-[#E3EFE6]">
              <h3 className="text-xl font-bold text-[#2F3E34]">
                Suggested Task List
              </h3>
              <p className="text-sm text-[#2F3E34]/80 mt-1">
                <span className="font-semibold">Reasoning:</span>{" "}
                {isLoadingSuggestions
                  ? suggestionsPhase === "waiting"
                    ? "waiting"
                    : "fetching data"
                  : suggestionsData.reasoning || "No reasoning returned."}
              </p>
            </div>

            <div className="p-5 min-h-[300px]">
              {suggestionsError && (
                <p className="text-sm text-red-600 mb-4">{suggestionsError}</p>
              )}

              <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                {/* Always render three containers while loading/empty to preserve expected UI structure. */}
                {(isLoadingSuggestions || suggestionsData.plans.length === 0
                  ? Array.from({ length: 3 }, (_, idx) => ({
                      plan_type: "fetching data",
                      stance: "fetching data",
                      actions: [] as SuggestedAction[],
                      _placeholderId: idx,
                    }))
                  : suggestionsData.plans.slice(0, 3)
                ).map((plan, pIdx) => (
                  <div
                    key={`${plan.plan_type}-${pIdx}`}
                    className="bg-white border-2 border-[#BFD8B8] rounded-xl p-4 flex flex-col h-full hover:border-[#7FB77E] transition-all shadow-sm"
                  >
                    <div className="mb-4">
                      <h4 className="text-lg font-bold text-[#2F3E34] lowercase">
                        {plan.plan_type}
                      </h4>
                      <p className="text-xs text-[#2F3E34]/70 mt-1 h-8">
                        stance: {plan.stance}
                      </p>
                      <div className="mt-3 inline-flex items-center justify-center bg-[#E3EFE6] text-[#2F3E34] text-xs font-bold px-2.5 py-1 rounded-full border border-[#BFD8B8]">
                        no. of tasks:{" "}
                        {isLoadingSuggestions
                          ? "fetching data"
                          : plan.actions.length}
                      </div>
                    </div>

                    <div className="flex-1 overflow-y-auto max-h-[160px] mb-5 space-y-2 pr-2 custom-scrollbar">
                      <div className="text-xs text-[#2F3E34]/80">
                        {"Fetching Task......"}
                      </div>
                      {isLoadingSuggestions ? (
                        <>
                          <div className="text-xs text-[#2F3E34]/80">
                            task name - fetching data
                          </div>
                          <div className="text-xs text-[#2F3E34]/80">
                            action - fetching data
                          </div>
                          <div className="text-xs text-[#2F3E34]/80">
                            hrs - fetching data
                          </div>
                        </>
                      ) : (
                        plan.actions.map((actionItem, actionIdx) => {
                          const mappedTask = taskLookup[actionItem.task_id];
                          const taskName =
                            mappedTask?.name ?? `task id ${actionItem.task_id}`;

                          return (
                            <div
                              key={`${actionItem.task_id}-${actionIdx}`}
                              className="text-xs text-[#2F3E34]/80 leading-snug border-b border-[#F4F7F5] pb-2 last:border-0"
                            >
                              <p>{taskName}</p>
                              <p>action - {actionItem.action}</p>
                              <p>
                                hrs -{" "}
                                {typeof actionItem.new_hours === "number"
                                  ? actionItem.new_hours
                                  : "n/a"}
                              </p>
                            </div>
                          );
                        })
                      )}
                      <div className="text-xs text-[#2F3E34]/80">{"}"}</div>
                    </div>

                    <button
                      onClick={() => handleSelectList(plan)}
                      disabled={isLoadingSuggestions}
                      className="w-full text-sm bg-[#E3EFE6] text-[#2F3E34] font-bold px-4 py-2.5 rounded-lg border border-[#BFD8B8] hover:bg-[#7FB77E] hover:text-white hover:border-[#7FB77E] transition-all mt-auto disabled:opacity-60 disabled:cursor-not-allowed disabled:hover:bg-[#E3EFE6] disabled:hover:text-[#2F3E34] disabled:hover:border-[#BFD8B8]"
                    >
                      Choose
                    </button>
                  </div>
                ))}
              </div>
            </div>

            <div className="p-4 border-t border-[#BFD8B8] bg-[#E3EFE6] flex justify-end">
              <button
                onClick={() => setShowSuggestions(false)}
                className="text-sm px-5 py-2 text-[#2F3E34] hover:bg-[#BFD8B8]/30 rounded-lg transition-colors font-medium"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Final Confirm Modal */}
      {showFinalConfirm && selectedPlan && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 bg-[#2F3E34]/60 backdrop-blur-sm">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-sm overflow-hidden animate-in zoom-in-95">
            <div className="p-6 text-center">
              <h3 className="text-xl font-bold text-[#2F3E34] mb-3">
                Confirm Plan Selection
              </h3>
              <p className="text-sm text-[#2F3E34]/80 mb-6">
                Are you sure you to add{" "}
                <span className="font-bold text-[#7FB77E]">
                  "{selectedPlan.plan_type}"
                </span>{" "}
                list containing{" "}
                <span className="font-bold">{selectedPlan.actions.length}</span>{" "}
                tasks as your to do list
              </p>

              <div className="flex gap-3 justify-center">
                <button
                  onClick={handleFinalCancel}
                  className="flex-1 px-4 py-2.5 rounded-lg border border-[#BFD8B8] text-[#2F3E34] hover:bg-[#F4F7F5] font-medium transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleFinalConfirm}
                  className="flex-1 px-4 py-2.5 rounded-lg bg-[#7FB77E] text-white hover:bg-[#68a367] font-medium transition-colors shadow-sm"
                >
                  Save Tasks
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
